// <auto-generated />
using Infra.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Ef.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domains.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Ref")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleTypeId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 38,
                            ArticleTypeId = 1,
                            Name = "apple",
                            Price = 10f,
                            Quantity = 6,
                            Ref = "0001"
                        },
                        new
                        {
                            Id = 1,
                            ArticleTypeId = 1,
                            Name = "apricot",
                            Price = 2f,
                            Quantity = 3,
                            Ref = "0002"
                        },
                        new
                        {
                            Id = 2,
                            ArticleTypeId = 1,
                            Name = "avocado",
                            Price = 7f,
                            Quantity = 4,
                            Ref = "0003"
                        },
                        new
                        {
                            Id = 3,
                            ArticleTypeId = 1,
                            Name = "banana",
                            Price = 15f,
                            Quantity = 6,
                            Ref = "0004"
                        },
                        new
                        {
                            Id = 4,
                            ArticleTypeId = 1,
                            Name = "bell pepper",
                            Price = 6f,
                            Quantity = 8,
                            Ref = "0005"
                        },
                        new
                        {
                            Id = 5,
                            ArticleTypeId = 1,
                            Name = "bilberry",
                            Price = 8f,
                            Quantity = 7,
                            Ref = "0006"
                        },
                        new
                        {
                            Id = 6,
                            ArticleTypeId = 1,
                            Name = "blackberry",
                            Price = 6f,
                            Quantity = 9,
                            Ref = "0007"
                        },
                        new
                        {
                            Id = 7,
                            ArticleTypeId = 1,
                            Name = "blackcurrant",
                            Price = 7f,
                            Quantity = 4,
                            Ref = "0008"
                        },
                        new
                        {
                            Id = 8,
                            ArticleTypeId = 1,
                            Name = "blueberry",
                            Price = 10f,
                            Quantity = 6,
                            Ref = "0009"
                        },
                        new
                        {
                            Id = 9,
                            ArticleTypeId = 1,
                            Name = "boysenberry",
                            Price = 12f,
                            Quantity = 7,
                            Ref = "00010"
                        },
                        new
                        {
                            Id = 10,
                            ArticleTypeId = 1,
                            Name = "breadfruit",
                            Price = 13f,
                            Quantity = 1,
                            Ref = "00011"
                        },
                        new
                        {
                            Id = 11,
                            ArticleTypeId = 1,
                            Name = "cantaloupe",
                            Price = 19f,
                            Quantity = 2,
                            Ref = "00012"
                        },
                        new
                        {
                            Id = 12,
                            ArticleTypeId = 1,
                            Name = "cherimoya",
                            Price = 15f,
                            Quantity = 3,
                            Ref = "00013"
                        },
                        new
                        {
                            Id = 13,
                            ArticleTypeId = 1,
                            Name = "cherry",
                            Price = 13f,
                            Quantity = 4,
                            Ref = "00014"
                        },
                        new
                        {
                            Id = 14,
                            ArticleTypeId = 1,
                            Name = "clementine",
                            Price = 12f,
                            Quantity = 5,
                            Ref = "00015"
                        },
                        new
                        {
                            Id = 15,
                            ArticleTypeId = 1,
                            Name = "cloudberry",
                            Price = 19f,
                            Quantity = 6,
                            Ref = "00016"
                        },
                        new
                        {
                            Id = 16,
                            ArticleTypeId = 1,
                            Name = "coconut",
                            Price = 14f,
                            Quantity = 7,
                            Ref = "00017"
                        },
                        new
                        {
                            Id = 17,
                            ArticleTypeId = 1,
                            Name = "cranberry",
                            Price = 16f,
                            Quantity = 8,
                            Ref = "00018"
                        },
                        new
                        {
                            Id = 18,
                            ArticleTypeId = 1,
                            Name = "cucumber",
                            Price = 12f,
                            Quantity = 9,
                            Ref = "00019"
                        },
                        new
                        {
                            Id = 19,
                            ArticleTypeId = 2,
                            Name = "Article1",
                            Price = 2f,
                            Quantity = 1,
                            Ref = "00020"
                        },
                        new
                        {
                            Id = 20,
                            ArticleTypeId = 2,
                            Name = "Article2",
                            Price = 3f,
                            Quantity = 2,
                            Ref = "00021"
                        },
                        new
                        {
                            Id = 21,
                            ArticleTypeId = 2,
                            Name = "Article3",
                            Price = 5f,
                            Quantity = 3,
                            Ref = "00022"
                        },
                        new
                        {
                            Id = 22,
                            ArticleTypeId = 2,
                            Name = "Article4",
                            Price = 9f,
                            Quantity = 4,
                            Ref = "00023"
                        },
                        new
                        {
                            Id = 23,
                            ArticleTypeId = 2,
                            Name = "Article5",
                            Price = 7f,
                            Quantity = 5,
                            Ref = "00024"
                        },
                        new
                        {
                            Id = 24,
                            ArticleTypeId = 2,
                            Name = "Article6",
                            Price = 5f,
                            Quantity = 6,
                            Ref = "00025"
                        },
                        new
                        {
                            Id = 25,
                            ArticleTypeId = 2,
                            Name = "Article7",
                            Price = 6f,
                            Quantity = 7,
                            Ref = "00026"
                        },
                        new
                        {
                            Id = 26,
                            ArticleTypeId = 2,
                            Name = "Article8",
                            Price = 1f,
                            Quantity = 8,
                            Ref = "00027"
                        },
                        new
                        {
                            Id = 27,
                            ArticleTypeId = 2,
                            Name = "Article9",
                            Price = 12f,
                            Quantity = 9,
                            Ref = "00028"
                        },
                        new
                        {
                            Id = 28,
                            ArticleTypeId = 2,
                            Name = "Article10",
                            Price = 15f,
                            Quantity = 1,
                            Ref = "00029"
                        },
                        new
                        {
                            Id = 29,
                            ArticleTypeId = 2,
                            Name = "Article11",
                            Price = 15f,
                            Quantity = 3,
                            Ref = "00030"
                        },
                        new
                        {
                            Id = 30,
                            ArticleTypeId = 2,
                            Name = "Article12",
                            Price = 13f,
                            Quantity = 9,
                            Ref = "00031"
                        },
                        new
                        {
                            Id = 31,
                            ArticleTypeId = 2,
                            Name = "Article13",
                            Price = 16f,
                            Quantity = 7,
                            Ref = "00032"
                        },
                        new
                        {
                            Id = 32,
                            ArticleTypeId = 2,
                            Name = "Article14",
                            Price = 19f,
                            Quantity = 5,
                            Ref = "00033"
                        },
                        new
                        {
                            Id = 33,
                            ArticleTypeId = 2,
                            Name = "Article15",
                            Price = 18f,
                            Quantity = 2,
                            Ref = "00034"
                        },
                        new
                        {
                            Id = 34,
                            ArticleTypeId = 2,
                            Name = "Article16",
                            Price = 8f,
                            Quantity = 2,
                            Ref = "00035"
                        },
                        new
                        {
                            Id = 35,
                            ArticleTypeId = 2,
                            Name = "Article17",
                            Price = 7f,
                            Quantity = 3,
                            Ref = "00036"
                        },
                        new
                        {
                            Id = 36,
                            ArticleTypeId = 2,
                            Name = "Article18",
                            Price = 6f,
                            Quantity = 8,
                            Ref = "00037"
                        },
                        new
                        {
                            Id = 37,
                            ArticleTypeId = 2,
                            Name = "Article19",
                            Price = 3f,
                            Quantity = 9,
                            Ref = "00038"
                        });
                });

            modelBuilder.Entity("Domains.Entities.ArticleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArticleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alimentaire"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Non alimentaire"
                        });
                });

            modelBuilder.Entity("Domains.Entities.Article", b =>
                {
                    b.HasOne("Domains.Entities.ArticleType", "ArticleType")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
